### ISSUE TITLE
Replace random recommendation button with reverse lookup

### ISSUE THREAD

**Issue by Mandelliant** [Mandelliant/nextbook-django#60]
Currently in `nextbook/index.html` the "Get another suggestion" button is currently built as follows:

```html
  <button type="button" value="Get another suggestion" onClick="window.location.reload()">Get another suggestion</button>
```

It should redirect to the same page again through a Django reverse url lookup

**Comment by philippeoz** [comment]
Can i help with this?

**Comment by Mandelliant** [comment]
@philippeoz sure, thanks for all of the help!
